# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Vagrant box type
  config.vm.box = "ubuntu/xenial64"
  # Vagrant box check for update
  config.vm.box_check_update = false

  # Vagrant box private network
  config.vm.network "private_network", ip: "192.168.27.27"

  # Vagrant box synced folder
  config.vm.synced_folder "./synced_with_vagrantbox", "/vagrant_data_host_sync"

   config.vm.provider "virtualbox" do |vbx|
     # Vagrant box display GUI
     vbx.gui = false

     # Vagrant box VM name 
     vbx.name = "ubuntu_docker_registry"

     # Customize memory on the VM:
     vbx.memory = 2048

     # Vagrant box customize cpu
     vbx.cpus = 2
   end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
